auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: localhost
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 1h
  max_chunk_age: 1h

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/cache
  filesystem:
    directory: /tmp/loki/chunks
  wal_directory: /tmp/loki/wal

limits_config:
  #allow_structured_metadata: false  # Prevents validation error

compactor:
  working_directory: /tmp/loki/compactor
